### ISSUE TITLE
Aneslastic mass continuity cost function is wrong with tensorflow

### ISSUE THREAD

**Issue by jm5791** [openradar/PyDDA#103]
Hi devs,

Do we agree that the anelastic mass conservation is wrong when using the tensorflow implementation ?
I mean that `dwdz * anel_term` should be `dwdz + anel_term`  in
https://github.com/openradar/PyDDA/blob/ba7e8a9a8e1712474a90c1e339969665b57716e2/pydda/cost_functions/_cost_functions_tensorflow.py#L534

Thanks

**Comment by rcjackson** [comment]
I'll put this fix in with #104! Thank you for pointing this out!

**Comment by rcjackson** [comment]
Fixed in #104! Closing!
