### ISSUE TITLE
ssl.SSLCertVerificationError when importing pydda

### ISSUE THREAD

**Issue by JoyceHuang228** [openradar/PyDDA#117]
Hello,
I installed successfully PyDDA with pip install.  I'm working in Linux environment.
Then when importing pydda in python (python 3.9.7), I got the following error:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

Could you please help with this issue? Thanks a lot.

**Comment by JoyceHuang228** [comment]
I tried again to install on my personal laptop. It works. Maybe this ssl issue depends on certain computer setup, instead of a general issue.
By the way, with conda install -c conda-forge pydda, we get the version 1.5.0. When can we install the version 2.0 with conda?
Thanks

**Comment by rcjackson** [comment]
Version 2.0 is available on conda, so that has been fixed!
