### ISSUE TITLE
CI fails with Python 3.5 due to dependency issues.

### ISSUE THREAD

**Issue by rcjackson** [openradar/PyDDA#39]
I will make the minimum version of Python be 3.6 for the next release. CI now fails for 3.5 due to incompatibility with eccodes.

**Comment by scollis** [comment]
Yeah, I would move on swiftly from 3.5. Many are dropping tests for 3.5 and focusing on 3.6 and 3.7

**Comment by rcjackson** [comment]
Resolved by #40. Closing.
