### ISSUE TITLE
ERA-Interim at end of life Aug 2019

### ISSUE THREAD

**Issue by rcjackson** [openradar/PyDDA#43]
Eventually, the ERA Interim module will need to be updated to support ERA5, as ERA-Interim is being deprecated at the end of August this year.

**Comment by Liuccuipping** [comment]
Is there a package for ERA5-wind initialization for available? I try to download a ERA5 file by myself, however, in the file of "wind_fields", there is a wrong in the row "height_flattened -= Grid.radar_altitude["data"]". Can you give me some advise?
