### ISSUE TITLE
this is a mistake

### ISSUE THREAD

**Issue by huyaox** [openradar/PyDDA#58]
hello！
when i run this “lat_min, lat_max, lon_min, lon_max = display.plot_grid('reflectivity', level=level, vmin=vmin, vmax=vmax,cmap = pyart.graph.cm.NWSRef)”，this is a mistake “can not unpack non-iterable NoneType object ” why？and how resolve it？thanks！

**Comment by rcjackson** [comment]
Hello, the display code is simply ran by doing "display.plot_grid('reflectivity', level=level, vmin=vmin, vmax=vmax,cmap = pyart.graph.cm.NWSRef)." The code will only return a matplotlib axis handle, not a 4-tuple.
