### ISSUE TITLE
Last radar has always zero weights

### ISSUE THREAD

**Issue by jm5791** [openradar/PyDDA#89]
Hi devs !

First of all, many thanks for making `pydda` available, it's a very interesting tool !

For information, during my different explorations and trials, I noticed that the [current implementation](https://github.com/openradar/PyDDA/blob/main/pydda/retrieval/wind_retrieve.py#L725-L769) of `retrieval.wind_retrieve._get_dd_wind_field_tensorflow()` always affect zero weights to the observation data associated to the last radar provided, when more than one radar are provided.

Note: the same seems to occur with the equivalent scipy implementation.

**Comment by rcjackson** [comment]
Hello. Thank you for bringing attention to this! I've released PyDDA 1.3.0, which fixes this issue in #90.
