### ISSUE TITLE
It is seem that there is a bug in / pydda / cost functions / cost functions.py?  it is should be corrected like this?

### ISSUE THREAD

**Issue by zk19991208** [openradar/PyDDA#94]
![微信图片_20230824165922](https://github.com/openradar/PyDDA/assets/49970499/8334ea65-dbf3-4f48-9623-23b7545c8248)
![微信图片_20230824170020](https://github.com/openradar/PyDDA/assets/49970499/6534caae-a22a-45d2-99c1-a3322993c71e)
The use of '_cost_functions_numpy. calculate_vertical_vorticity-gradient' should be identifed with its usage.

**Comment by rcjackson** [comment]
What error is being thrown when you try to use the vorticity constraint? Could you be more specific about what the syntax error is? It's difficult to see any error with the code the way this is presented.

**Comment by zk19991208** [comment]
Thanks for the reply, Figure 2 _cost_functions_numpy.calculate_vertical_vorticity_cost doesn't have a keyword argument upper_bc but Figure 1 has one.It made my code wrong.
![mmexport1693077130077](https://github.com/openradar/PyDDA/assets/49970499/b548a644-ecc3-44f1-9a63-28dad145ff1f)

**Comment by rcjackson** [comment]
I've fixed this with PR #95 !
